# -------------------------------------------------------------------------------------------------
# INPUT
# -------------------------------------------------------------------------------------------------
input {
# Keyboard
kb_layout = us
kb_options =
resolve_binds_by_sym = false
numlock_by_default = true
repeat_rate = 35
repeat_delay = 250
# Mouse & Pointer
follow_mouse = 1
sensitivity = 0
accel_profile = adaptive
force_no_accel = false
left_handed = false
mouse_refocus = true
# Scrolling
natural_scroll = false
scroll_method = 2fg
scroll_button = 0
scroll_button_lock = false
# Touchpad
    touchpad {
natural_scroll = true
disable_while_typing = true
tap-to-click = true
clickfinger_behavior = false
drag_lock = false
    }
}
# -------------------------------------------------------------------------------------------------
# CURSOR
# -------------------------------------------------------------------------------------------------
cursor {
sync_gsettings_theme = true
no_hardware_cursors = 2
use_cpu_buffer = 2
hide_on_key_press = false
inactive_timeout = 0
warp_on_change_workspace = 0
no_break_fs_vrr = 2
zoom_factor = 1.0
}
# -------------------------------------------------------------------------------------------------
# GESTURES
# -------------------------------------------------------------------------------------------------
gestures {
workspace_swipe_distance = 300
workspace_swipe_cancel_ratio = 0.5
workspace_swipe_invert = true
workspace_swipe_create_new = true
workspace_swipe_forever = false
}
# -------------------------------------------------------------------------------------------------
# PER-DEVICE OVERRIDES
# -------------------------------------------------------------------------------------------------
device {
    name = asuf1205:00-2808:0106-touchpad
    accel_profile = adaptive
    sensitivity = 0
}
device {
    name = asuf1205:00-2808:0106-mouse
    accel_profile = flat
    sensitivity = 0
}
device {
    name = logitech-g304-1
    accel_profile = flat
    sensitivity = 0
}